# Generated by Django 4.2.2 on 2023-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_apply_applied_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='mobile',
        ),
    ]
